```{r}
#~~~~~~~~~~~#
#~~~Setup~~~#
#~~~~~~~~~~~#
#~~~Clear Workspace~~~#
rm(list=ls()) 

#~~~Import Data~~~#
#import packages
library('tidyverse')
library('readxl')
library('lubridate')

#~~~Variables to Edit~~~#
mainPath <- 'C:/R/DO Check/' #new csv's will be saved to here

fileName <- 'CM.RRI.data.csv' #name of data file
```

```{r}
#~~~~~~~~~~~~~~~~~~#
#~~~Read In Data~~~#
#~~~~~~~~~~~~~~~~~~#
#data filepath
filePath <- paste(mainPath,fileName,sep = '')

#read in data
doDatRaw <- read_csv(filePath)

#drop qual column
keepVars <- c('station','date.time','year','season','DO')
doDat <- doDatRaw[keepVars]

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~Calculate % Under Threshold~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#grab lists of variables
stations <- unique(doDat$station)
seasons <- unique(doDat$season)
years <- unique(doDat$year)

#initiate empty df
underDf <- NULL

#initiate for loops
for (stat in stations) { #this a for loop, it goes through the list of stations
  for (sea in seasons) { #before moving to next station, goes through list of seasons
    for (yr in years) { #before going to next season, goes through list of years
      
      #create name for saving 
      name <- paste(stat,sea,yr,sep = '')
      
      #create filtered df (overwritten during each iteration of the nested for loop)
      df <-
        doDat %>%
        filter(station == stat &
                 season == sea &
                 year == yr &
                 !is.na(DO))
      
      #assign threshold based on fall/summer
      if (grepl('Fall',name)) { #based on if fall is in the variable 'name'
        threshold <- 6 
      } else {
        threshold <- 5
      }
    
      #do the calculation
      countBelow <- nrow(df[df['DO'] < threshold,]) #comma tells it to call rows, not columns
      countTotal <- nrow(df)
      perUnder <- round(countBelow/(countTotal)*100,2)
      
      #bind row to output df
      underDf <- rbind(underDf, data.frame('station' = name, 'percent under threshold' = perUnder))
      }
  }
}

#create output file path
underPath <- paste(mainPath,'percentUnder.csv',sep = '')

#append output df to text file
write.table(
  underDf,
  underPath,
  sep = ',',
  col.names = TRUE,
  row.names = FALSE,
  quote = FALSE)
```

```{r}
#~~~~~~~~~~~~~~~~~~~~~~#
#~~~Compare Stations~~~#
#~~~~~~~~~~~~~~~~~~~~~~#
#initiate empty df
compDf <- NULL

for (sea in seasons) {
  for (yr in years) {
    #create name for saving 
    name <- paste(sea,yr,sep = '')
    
    #create filtered dfs
    dfFourty <-
      doDat %>%
      filter(station == 'CM40' &
               season == sea &
               year == yr &
               !is.na(DO))
    
    dfRRI <-
      doDat %>%
      filter(station == 'CM44_RRI' &
               season == sea &
               year == yr &
               !is.na(DO))
    
    
    #change dates columns to type(datetime) (or whatevs R uses :/) and round to nearest 15min
    dfFourty$date.time <- parse_date_time(dfFourty$date.time,'mdy HM')
    dfFourty$date.time <- round_date(dfFourty$date.time, '15 minutes')

    #same, but for RRI, accounting for the fact that in '07 it was collected hourly
    if (yr == '2007') {
      dfRRI$date.time <- parse_date_time(dfRRI$date.time,'mdy HM')
      dfRRI$date.time <- round_date(dfRRI$date.time, '1 hour')
    } else {
      dfRRI$date.time <- parse_date_time(dfRRI$date.time,'mdy HM')
      dfRRI$date.time <- round_date(dfRRI$date.time, '15 minutes')
    }

    #assign threshold based on fall/summer
    if (grepl('Fall',name)) {
      threshold <- 6
    } else {
      threshold <- 5
    }
    
    #merge the two dfs
    dfMerge <- merge(dfFourty,dfRRI,by = c('season','year','date.time'))
    
    #initalize counts
    doBoth <- 0
    doRRI <- 0
    doFourty <- 0
    
    #start for loop (element-wise :/)
    for (i in 1:nrow(dfMerge)) {
    #populate the count variables
      if ((dfMerge[i,]['DO.x'][[1]] < threshold) && (dfMerge[i,]['DO.y'][[1]] < threshold)) {
        doBoth = doBoth + 1
      } else if ((dfMerge[i,]['DO.x'][[1]] < threshold) && (dfMerge[i,]['DO.y'][[1]] >= threshold)) {
        doFourty = doFourty + 1
      } else if ((dfMerge[i,]['DO.x'][[1]] >= threshold) && (dfMerge[i,]['DO.y'][[1]] < threshold)) {
        doRRI = doRRI + 1
      }
    
    }
    
    #calculate percents
    calcBoth <- round(doBoth/nrow(dfMerge) * 100,2)
    calcFourty <- round(doFourty/nrow(dfMerge) * 100,2)
    calcRRI <- round(doRRI/nrow(dfMerge) * 100,2)
    
    #bind rows to output df
    compDf <-
      rbind(
        compDf,
        data.frame(
          'time period' = name,
          'both under threshold' = calcBoth,
          'fourty under threshold' = calcFourty,
          'RRI under threshold' = calcRRI))
    
  }
}

#create output file path
compPath <- paste(mainPath,'percentCompare.csv',sep = '')


#append output df to text file
write.table(
  compDf,
  compPath,
  sep = ',',
  col.names = TRUE,
  row.names = FALSE,
  quote = FALSE)

```

